# Generated by Django 5.0.6 on 2026-02-07 18:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='configuracion_principal', max_length=80, unique=True)),
                ('texto_bienvenida', models.CharField(default='Bienvenido a la encuesta.', max_length=255)),
                ('texto_instrucciones', models.CharField(default='Seleccione una opcion del 1 al 5 para cada pregunta.', max_length=255)),
                ('texto_agradecimiento', models.CharField(default='Gracias por tu respuesta.', max_length=255)),
                ('pregunta_abierta_activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuracion de encuesta',
                'verbose_name_plural': 'Configuracion de encuesta',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('modo_asignacion', models.CharField(choices=[('manual', 'Manual'), ('horario', 'Por horario')], default='horario', max_length=20)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ubicacion_referencial', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comedores', to='encuestas.sede')),
            ],
            options={
                'ordering': ['sede__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('satisfaccion_general', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('calidad_comida', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('variedad_menu', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('limpieza_comedor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tiempo_atencion_fila', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='encuestas.comedor')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='encuestas.sede')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='encuestas.turno')),
            ],
            options={
                'ordering': ['-fecha_hora_registro'],
            },
        ),
        migrations.CreateModel(
            name='PuntoCaptura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntos_captura', to='encuestas.comedor')),
                ('turno_defecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_captura_por_defecto', to='encuestas.turno')),
            ],
            options={
                'ordering': ['identificador'],
            },
        ),
        migrations.AddConstraint(
            model_name='comedor',
            constraint=models.UniqueConstraint(fields=('sede', 'nombre'), name='unique_comedor_por_sede'),
        ),
    ]
